### ISSUE TITLE
Change periodicity of Pan-PMC meetings to 2x a quarter

### ISSUE THREAD

**Issue by brooklynrob** [finos/finos-pmcs#10]
Should we change periodicity of Pan-PMC meetings to 2x a quarter, perhaps 2-3 weeks before board meeting, and then 2-3 weeks after? One less meeting per quarter.

**Comment by brooklynrob** [comment]
One standing topic I think we should add to our Pan-PMCs, with @mcleo-d 's help/leadership, is program and individual project plans, to attract contributors and build community (essentially product/community marketing).

**Comment by rikoe** [comment]
I am supportive of reducing the frequency.

**Comment by jbjonesjr** [comment]
I like the idea of moving it to be more board-meeting centric, and to continue to use issues/etc in the gap time. 

Only caveat I'd throw out if there needs to be consideration for other major foundation events (including OSSF, Members meeting, etc) that could involve lots of program participations. That could be worth an extra meeting (or discussion of some sort)

**Comment by lspiro-Tick42** [comment]
+1
