### ISSUE TITLE
2019 Program Roadmaps Built by PMCs w/ Project and Socialized w/ FINOS Commuinty

### ISSUE THREAD

**Issue by aitana16** [finos/finos-pmcs#11]
- [ ] DAV
- [ ] DEG
- [ ] DT
- [ ] FDC3
- [ ] FDX
- [ ] FO
- [ ] Hadouken
- [x] Plexus
- [ ] Symphony
- [ ] Voice

**Comment by brooklynrob** [comment]
See too related issue about defining OKRs: https://github.com/finos/finos-pmcs/issues/12

**Comment by brooklynrob** [comment]
Closing this now as this for 2019
