### ISSUE TITLE
OKRs defined for 2019 roadmaps by PMCs and reviewed with FINOS Team

### ISSUE THREAD

**Issue by aitana16** [finos/finos-pmcs#12]
Have contextualized their 2019 roadmap in OKR terms 

 ("Review and reaffirm objectives on which your program roadmap has been built")

- [ ] DAV
- [ ] DEG
- [ ] DT
- [x] FDC3
- [ ] FDX
- [ ] FO
- [ ] Hadouken
- [ ] Plexus
- [ ] Symphony
- [ ] Voice

**Comment by brooklynrob** [comment]
Note sure this was done consistently or ubiquitously across programs, but given this was OKR definition for 2019 and it's now 2020 I'm moving this to done on the kanban and closing this issue.
