### ISSUE TITLE
January 2020 Board Updates

### ISSUE THREAD

**Issue by aitana16** [finos/finos-pmcs#17]
**Board Update Slide**
- [ ] DAV
- [ ] DEG
- [x] DT
- [x] FDC3
- [x] FDX
- [x] FO
- [ ] Hadouken 
- [x] Plexus
- [x] Symphony
- [x] Voice

**Comment by brooklynrob** [comment]
@aitana16 Before we close this issue, can you check that the list accurately reflects who ended up turning in their required quarterly board update health check?

**Comment by aitana16** [comment]
@brooklynrob I have updated the list and will close this issue now.
