### ISSUE TITLE
2019 Program and Projects Roadmap Progress reviews

### ISSUE THREAD

**Issue by brooklynrob** [finos/finos-pmcs#18]
**2019 Roadmap REVIEW**
- [ ] DAV
- [ ] DEG
- [x] DT
- [x] FDC3
- [ ] FDX
- [x] FO
- [ ] Hadouken 
- [x] Plexus
- [x] Symphony
- [x] Voice

**Comment by brooklynrob** [comment]
@aitana16 Could you check that this list is correct/updated? Which programs did not submit 2019 progress reviews for the board meeting?

**Comment by aitana16** [comment]
@brooklynrob the list is now up to date. I will close this issue now.
