### ISSUE TITLE
Suggest Topics for February 2020 (2020.2.18) Pan-PMCs Meeting

### ISSUE THREAD

**Issue by brooklynrob** [finos/finos-pmcs#25]
* Board Meeting Debrief
   * Q1 Priority Projects

_What else?_

**Comment by brooklynrob** [comment]
One suggested topic. Looking at [metrics.finos.org](metrics.finos.org), there is a bit of trend developing that we're getting comparatively few pull requests of code to existing projects from our non-bank members just now (w/ some notable exceptions).

That may be a good problem to have in one sense but I'm wondering if there's more we can do to increase code contributions to existing projects from our non-bank members, especially our larger tech company members and some of our service providers (again, there are exceptions).

**Comment by mindthegab** [comment]
Couple of suggested topics you might consider would be:

- update PMC on forming and incubating focus projects for Q1
- review open CONTRIBs (eg SEA, data hub, etc) 
- reviewing comments on Program removal RFC and come to consensus (stretch goal: start thinking about a potential theme taxonomy) 
- review draft KPIs and get input from
community on “community KPIs)
- How do we identify/prioritize/focus on Industry wide business challenges review per board request? (Egidea of a technical steering committee )
-

**Comment by brooklynrob** [comment]
Another question we may want to start to address is if these Pan-PMC meetings have outlived their usefulness, and perhaps are more trouble than they are worth, especially given it appears increasingly likely that it may be decided that we get rid of programs altogether. 

@aitana16 and I put fair bit of time preparing for these meetings, conducting them, and doing the follow-up but I wonder if it's worth the investment of time at this point. Are there meetings that the PMCs value?

And once programs are gone, what would this meeting transform to? A meeting of the leads of all 45 or so non-archived projects?

Let's also discuss tomorrow if he should terminate this meeting series.

**Comment by mcleo-d** [comment]
The following has been added to the Google Slides 👍 

> One suggested topic. Looking at [metrics.finos.org](metrics.finos.org), there is a bit of trend developing that we're getting comparatively few pull requests of code to existing projects from our non-bank members just now (w/ some notable exceptions).
> 
> That may be a good problem to have in one sense but I'm wondering if there's more we can do to increase code contributions to existing projects from our non-bank members, especially our larger tech company members and some of our service providers (again, there are exceptions).

**Comment by mcleo-d** [comment]
The following have been added to the Google Slides 👍 

> Couple of suggested topics you might consider would be:
> 
> * update PMC on forming and incubating focus projects for Q1
> * review open CONTRIBs (eg SEA, data hub, etc)
> * reviewing comments on Program removal RFC and come to consensus (stretch goal: start thinking about a potential theme taxonomy)
> * review draft KPIs and get input from
>   community on “community KPIs)
> * How do we identify/prioritize/focus on Industry wide business challenges review per board request? (Egidea of a technical steering committee )

**Comment by mcleo-d** [comment]
The following has been added to the Google Slides 👍 

> Another question we may want to start to address is if these Pan-PMC meetings have outlived their usefulness, and perhaps are more trouble than they are worth, especially given it appears increasingly likely that it may be decided that we get rid of programs altogether.
> 
> @aitana16 and I put fair bit of time preparing for these meetings, conducting them, and doing the follow-up but I wonder if it's worth the investment of time at this point. Are there meetings that the PMCs value?
> 
> And once programs are gone, what would this meeting transform to? A meeting of the leads of all 45 or so non-archived projects?
> 
> Let's also discuss tomorrow if he should terminate this meeting series.

**Comment by tschady** [comment]
I value the broadcast info, particularly the board updates, but I would prefer to read these than listen in on a synchronous call.

**Comment by brooklynrob** [comment]
@tschady Thanks Tom. A few things:

1. The primary board feedback was that the time the programs/projects updates take much time (as context the project updates took 35 minutes in January; the overall board meeting is 4 hours). We probably at least need to re-imagine how the updates on the project portfolio are presented (as context, I usually do it; in January I did about 2/3 and James did 1/3) as the "too much time" feedback I think in part reflect the board view that they don't see much value in the updates themselves, or least much in value in how I'm delivering them. I'm guessing we probably need to find a way to cut back the projects updates to, I'm guessing, maybe just 10-15 minutes, if not perhaps cutting out the programs/projects updates altogether at the board meeting. Maybe akin to your suggestion re reading, maybe we just send an update to the board for them to read about the projects, and now discuss the projects at all. 

2. Related, we continue to get feedback from PMCs that preparing the quarterly health checks is still too much overhead and work. Given much of that material ends up going to the appendix of the board deck, perhaps we need to find a way to cull that back, perhaps getting rid of the program health checks altogether. We also need to start thinking about how project updates get done after programs and PMCs have been eliminated, and by whom.

3. Also related, it feels like the Pan-PMC meeting is a meeting that while on paper to me at least made sense (i.e., a forum whereby the 10 PMCs could meet together to talk and compare notes), it's largely become a meeting where @aitana16 and I prepare a PowerPoint style deck that we read out to the community ("broadcast" as you put it Tom). I think we should discuss tomorrow if perhaps tomorrow's meeting should be the last Pan-PMC meeting, at least for now, to potentially be replaced by something new in the post-Programs world. At a minimum the Pan-PMC meeting feels like it needs to be re-imagined. 

From my vantage, I'd like continue to remove any and everything in program operations that is not truly critical (i.e., get rid of any "muda") and lots of what we have right now in terms of program operations and status reports seems like it's over time become muda (i.e., stuff we're doing that isn't creating much value). 

Let's discuss more tomorrow. Thanks for the feedback.

**Comment by brooklynrob** [comment]
@toshaellison @grizzwolf Anything we should include about OSSF?

**Comment by mcleo-d** [comment]
Meeting minutes approved for 2020-02-07 during PMC call
* https://github.com/finos/finos-pmcs/blob/master/docs/2020-01-07-Pan-PMC-Meeting.md

**Comment by aitana16** [comment]
Closing this issue now as the agenda was completed on 2/17, meeting took place on 2/18. Meeting minutes can be found here: https://github.com/finos/finos-pmcs/blob/master/docs/2020-02-18-Pan-PMC-Meeting.md (cc @brooklynrob @mcleo-d)
