### ISSUE TITLE
RFC : Discontinue FINOS Pan-PMC Meetings with Immediate Effect

### ISSUE THREAD

**Issue by mcleo-d** [finos/finos-pmcs#26]
### RFC Description
During the 18th February 2020 Pan-PMC meeting it was agreed there are more affective ways for FINOS and the PMC community to communicate and feedback on FINOS related activity. 

This is further compounded by the level of effort to prepare for the meeting verses PMC attendance when FINOS updates are presented.

This RFC states all FINOS Pan-PMC meetings will discontinue with immediate effect unless there are overruling objections made in the comments of this GitHub issue.

Please make comments below if there are objections to FINOS discontinuing the Pan-PMC meetings with immediate effect.

**Comment by jbjonesjr** [comment]
👍 :wave: Thanks for all the work supporting these meetings @brooklynrob and @aitana16

**Comment by tschady** [comment]
Please continue to email out the information you present from the slidedeck.  It's valuable.

**Comment by mindthegab** [comment]
Thanks @tschady and @jbjonesjr. 

I suggest we do have one last meeting next week to give a close to the [Program Removal proposal](https://github.com/finos/finos-pmcs/pull/22) as part of a more holistic review and simplification of our community governance.

And yes we'll continue trickling information.

**Comment by jbjonesjr** [comment]
> I suggest we do have one last meeting 

👍

**Comment by mindthegab** [comment]
As suggested we will discontinue Pan-PMC meetings, but we will:

1. Continue to email out periodic updates per @tschady suggestion.
2. Explore the creation of a TAC as discussed in the last [pan PMC meeting](https://github.com/finos/finos-pmcs/blob/master/docs/2020-03-31-Pan-PMC-Meeting.md)
3. Enact the softer approach of Program deprecation (as opposed to "removal") outlined and [socialized with Community](https://groups.google.com/a/finos.org/forum/#!topic/pmcs/e7dpjwbC9q8)

@mcleo-d please close this RFC.
