### ISSUE TITLE
April 2020 Board updates 

### ISSUE THREAD

**Issue by aitana16** [finos/finos-pmcs#30]
### Program & FINOS Contact 

- [ ]  DAV |  @mcleo-d 
- [ ]  DEG | @brooklynrob 
- [x]  DT | @mcleo-d 
- [x]  FDC3 | @brooklynrob 
- [ ]  FDX | @mcleo-d 
- [x]  FO | @brooklynrob 
- [ ]  Hadouken | @brooklynrob 
- [x]  Plexus | @mcleo-d 
- [x]  Symphony | @mcleo-d
- [x]  Voice | @brooklynrob 

### Project & FINOS Contact
- [ ] Plexus |  @mcleo-d 
- [ ] Citi Synthetic Data | @mcleo-d 
- [ ] Perspective | @mcleo-d 
- [ ] Alloy | @brooklynrob

**Comment by mcleo-d** [comment]
@mcleo-d to add focused projects to the list ...

- [ ] Plexus
- [ ] Citi Synthetic Data
- [ ] Perspective
- [ ] Alloy

**Comment by mcleo-d** [comment]
@mcleo-d has scheduled individual update and feedback sessions for the following PMC leads for Wednesday 8th April to confirm the content of @aitana16 emails were received and there are no future questions.

* **DAV** - Meeting scheduled with Neil Slinger for 8th April 2020
* **DT** - Meeting scheduled with Alvin Shih for 8th April 2020
* **FDX** - Meeting scheduled with Jamie Jones for 8th April 2020
* **Plexus** - Meeting scheduled with Jamie Jones for 8th April 2020
* **Symphony** - Meeting scheduled with Umesh Patel for 8th April 2020

**Comment by brooklynrob** [comment]
@paulwhitby @aitana16 @mcleo-d Can someone point me to Q2 Plexus report? What I'm looking at appears to be the same as the Q1 report.

**Comment by brooklynrob** [comment]
Connected with @hammadnyc earlier today who is working on the FO report. I'll complete the section for Alloy (@beekemarie @pierredebelen)

**Comment by brooklynrob** [comment]
@paulwhitby @mcleo-d, @aitana16 -- pointed me to Q2 status. See my email re overall status color.

**Comment by brooklynrob** [comment]
Still no @finos/hadouken-program report as of 5pm ET Friday; reached out to @finos/hadouken-pmc to check in on status. @chuckdoerr @bschwinn @dkerr-scottlogic @mwardRH @nkolba

**Comment by brooklynrob** [comment]
Still no @finos/fdx-program report at of 6pm ET Friday. Reached out to @finos/fdx-pmc to check in on status. @jbjonesjr @copiesofcopies @maoo @bingenito @git-hub-forwork1 @ColinEberhardt @davidwatkins73

**Comment by jbjonesjr** [comment]
👋 In progress! 👋

**Comment by aitana16** [comment]
Closing this issue as the board deck has been finalized and sent out.
