### ISSUE TITLE
Request to restart monthly FINOS Waltz project calls

### ISSUE THREAD

**Issue by mcleo-d** [finos/finos-pmcs#302]
## Request to restart monthly FINOS Waltz project calls

The NatWest OSPO would like to request a monthly Waltz project call to support the adoption of the project. 

The start date and agenda management can be discussed and agreed once the appetite of FINOS, @davidwatkins73 and @JWoodland-Scott is understood.

Thanks for your consideration.

James.

**Comment by mindthegab** [comment]
Thanks @mcleo-d - I think this issue would be better served in the Waltz repo.

Also tagging @finos/waltz-maintainers for visibility.

**Comment by mcleo-d** [comment]
This issue has been transferred here - https://github.com/finos/waltz/issues/7011
