### ISSUE TITLE
Discontinue PMC meetings for Voice, Plexus and DAV

### ISSUE THREAD

**Issue by mindthegab** [finos/finos-pmcs#33]
Based on decisions made in https://github.com/finos/finos-pmcs/issues/31 by PMCs, per Program deprecation approved by the Board, please:

- Cancel upcoming PMC meetings from calendar and webex (if meetings exist)

- Notify respective PMC lists these changes are being operationalize and reference this issue https://github.com/finos/finos-pmcs/issues/31 for all details (cc leadership team) 

/cc FYI (@lspiro-Tick42 @paulwhitby @rhyddian, @tschady @neilslinger)

**Comment by tschady** [comment]
email announcing disbanded Voice Program sent to voice@finos.org

**Comment by aitana16** [comment]
- DAV: does not have recurring meetings on the FINOS Programs Calendar

- Voice: does not have recurring meetings on the FINOS Programs Calendar

- Plexus: existing recurring meetings have been deleted from webex and FINOS Programs Calendar. An e-mail notifying the Plexus PMC and referencing issue [#31](https://github.com/finos/finos-pmcs/issues/31) has been sent to plx-pmc@finos.org 

Closing this issue now
