### ISSUE TITLE
Morph DAV and Voice to be top level projects

### ISSUE THREAD

**Issue by mindthegab** [finos/finos-pmcs#34]
- [x] Perspective becomes top level (/cc @finos/dav-pmc @neilslinger)
- [x] Projects in the Voice Program become top level (/cc @tschady @finos/voice-pmc)

**Comment by tschady** [comment]
@mindthegab Voice projects already were top-level. 
I have deleted our program's meta-project.  
https://github.com/finos-voice/ is now empty and can be deleted.

**Comment by maoo** [comment]
TY @tschady ! Few notes:
1. Although Voice was already using github.com/finos , all Voice projects would still show up as Voice program on metrics.finos.org and finos.github.io; now we updated our internal metadata, so soon (1/2 days max) we should see the changes reflected across all our systems
2. By default we keep github.com/finos-voice, to preserve Git redirects, but if you think that isn't necessary, I think there's no harm proceeding with deletion. @mindthegab - any strong feelings about this?

**Comment by tschady** [comment]
I'd delete it @maoo.  Nobody needs the redirect.

**Comment by mindthegab** [comment]
I would rather leave the orgs right now until we do a full cleanup of website and wiki, because there might be existing links. This will happen over the next months, so I'd rather be conservative right now and allow us to execute on the "cleanup" knowing we haven't broken any link right now. We can remove deprecated orgs at a later stage (just put a notice in the description).

**Comment by maoo** [comment]
All repo moved, closing issue. TY!
