### ISSUE TITLE
Disband DEG program

### ISSUE THREAD

**Issue by mindthegab** [finos/finos-pmcs#35]
There really are no Projects to top level @maoo so not sure anything needs to be done from your side.

@aitana16 not sure if there are meetings or any other infrastructure (mailing lists aside, those we can clean up later) to clean up this Program disbands. 

Assigning this issue to both of you @maoo  @aitana16 as a placeholder but please feel free to close if nothing has to be done.

**Comment by maoo** [comment]
Nothing to do on the infra/tech/github side, up to @aitana16 !

**Comment by maoo** [comment]
Actually, 1 thing. Would be great if @amberella and @patrickmn could be [covered by our CLA](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements), so we can preserve them as [FINOS GitHub org members](https://github.com/orgs/finos/people).

If not possible, I'd remove them for now; given that they are not active on any of our repos, nothing will change.

TY!

**Comment by aitana16** [comment]
@maoo @mindthegab there are no DEG meetings, so back to you on whether you will preserve amber and patrick as FINOS Github org members. I'm happy to help with anything I can, please let me know

**Comment by mindthegab** [comment]
@amberella @patrickmn you good to sign our CLA as per @maoo suggestion above? Or otherwise we can close this issue.

**Comment by mindthegab** [comment]
@maoo Clovyr signed a CLA in 2019. I've just looped you in the email so you can update our records. 

This issue can be closed.

**Comment by maoo** [comment]
Thanks all! Records updated re. Clovyr CCLA
