### ISSUE TITLE
Morph FDC3 to be a single project with multiple meetings

### ISSUE THREAD

**Issue by mindthegab** [finos/finos-pmcs#37]
Per las[t week's FDC3 PMC meeting](https://finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/1584464025/2020-05-01+Meeting) (/cc @finos/fdc3-pmc @nkolba @rikoe @donbasuno), the decision was made to disband the FDC3 program as a governance body, but for PMC members to continue meeting periodically as the "Product Management Committee" for the FDC3 project to provide marketing, comms and community engagement oversight.

In terms of FINOS changes, @maoo and @aitana16 please do the following:

- FDC3 becomes a top level project
- The activity currently related to PMC (wiki, email list, meetings, etc) should continue to be tracked and be now associated to the FDC3 project from now on (just as one additional meeting)
- @aitana16 has the details on other, tangential, changes happening on the mailing lists, and the transition of the wiki to github, so I'll let her drive the rest of the changes that might be needed in metadata here, as well as if there are any other changes in meeting schedules / etc.

Please @nkolba @rikoe @donbasuno chime in if I have misrepresented something.

**Comment by maoo** [comment]
Internal metadata updated (pending update on metrics.finos.org)

**Comment by aitana16** [comment]
Hi @mindthegab @maoo I have done the following and I think there's nothing left to do on my side to close this issue:

### **Working Group Mailing lists:** (AppdD, API, Context Data, Intents, Context Data & Intents, Use Case)
- [ ] **removed all members** but Rob Underwood, James McLeod, Aitana Myohl and barnowl@bitergia.com
- [ ] set up the following **auto-reply message** to be sent out to anyone e-mailing the below Google Group Mailing lists: _"Hi, as of May 7th 2020, this mailing list has been deprecated. All FINOS FDC3 project-related communications are now conducted through fdc3@finos.org. Please e-mail help@finos.org if you need help."_
- [ ] added **[ARCHIVED]** to the beginning of the Google Group name

### **FDC3 General Mailing list (fdc3@finos.org)** 
- [ ] **Identified the contacts** that are in any of the currently existing WG mailing lists but not in the fdc3@finos.org General Mailing list 
- [ ] **Added** those **contacts** to fdc3@finos.org
- [ ] When adding them to fdc3@finos.org, I have shared the following message:   _"Hi, as of May 7th 2020, all FDC3 Working Group Mailing lists (i.e. AppdD, API, Context Data, Intents, Context Data & Intents, and Use Cases Working Group Mailing lists) have been consolidated into the FDC3 General Mailing list (fdc3@finos.org), which you are now being added to. Please e-mail help@finos.org if you'd like to unsubscribe."_

### **FDC3 Standard Working Group** 
- [ ] Set up a recurring (monthly on the 4th Thursday, at 10am) calendar invite on the FINOS Programs Calendar 
- [ ] added fdc3@finos.org to the invite.
- [ ] added fdc3-pmc@finos.org to the invite

### **FDC3 Wiki** 
- [ ] On each WG's homepage, I have replaced the links to specific Google Group mailing lists for links to fdc3@finos.org

**Comment by maoo** [comment]
https://metrics.finos.org reindexed! FDC3 now shows as TopLevel project

**Comment by maoo** [comment]
TODO for @maoo - The activity currently related to PMC (wiki, email list, meetings, etc) should continue to be tracked and be now associated to the FDC3 project from now on (just as one additional meeting) - update FDC3 project metadata accordingly.

**Comment by maoo** [comment]
The following lists activities (current and past) are now associated to FDC3 Top Level project:
- fdc3-pmc@finos.org
- fdc3-pmc-private@finos.org
- fdc3@finos.org

Changes on metrics.finos.org will be reflected in the next 1/2 days. I'll close this issue when changes are applied.

**Comment by maoo** [comment]
Done! metrics.finos.org is now updated!
