### ISSUE TITLE
Morph Symphony Program to multiple top level projects

### ISSUE THREAD

**Issue by mindthegab** [finos/finos-pmcs#38]
Per today's [PMCs vote](https://groups.google.com/a/finos.org/forum/#!topic/symphony-pmc/_qnCcDQp3xI) (/cc @finos/symphony-pmc), the Symphony Program decided to continue as independent top level projects.

@maoo please:
- Make all Symphony projects top level
- Leave projects in the current github symphonyoss org
- @aitana16 don't think the PMC was meeting at all but tagging you here to double check

**Comment by aitana16** [comment]
thanks @mindthegab , I can confirm there's no Symphony meetings on the FINOS programs calendar

**Comment by maoo** [comment]
Internal metadata updated (pending update on metrics.finos.org). @mindthegab @aitana16 - are we ok to close the issue? 👍 from me.

**Comment by aitana16** [comment]
👍from me as well

**Comment by maoo** [comment]
https://metrics.finos.org reindexed! Symphony projects now shows as TopLevel

**Comment by finos-admin** [comment]
@aitana16 can we put a note on the Symphony Program and PMC akin to what done in the [Data Tech Program](https://finosfoundation.atlassian.net/wiki/spaces/DT/overview?homepageId=327090198)?

**Comment by aitana16** [comment]
@mindthegab done. See the Symphony [Program](https://finosfoundation.atlassian.net/wiki/spaces/SYM/overview?homepageId=21823502) and and [PMC](https://finosfoundation.atlassian.net/wiki/spaces/SYM/pages/40534019/PMC) homepages. Closing this issue now.
