### ISSUE TITLE
Morph Data Technologies Program into Multiple Projects

### ISSUE THREAD

**Issue by mindthegab** [finos/finos-pmcs#41]
Per VOTE on [Data Tech PMC list](https://groups.google.com/a/finos.org/forum/#!topic/data-tech-pmc/S76HfDFf7zY), the Data Technologies PMC has decided to disband and contained projects to continue as Top-Level. 

So please execute on the following tasks:
- [x] @maoo Morph all project to be "Top Level" project in our finos.github.io catalog, retaining the existing lifecycle stage
- [x] @aitana16 cancel ongoing PMC meetings on webex
- [x] @aitana16 - add to the Program Wiki page the notice that the program has been disbanded and projects continue as top level projects.

/CC @finos/dt-pmc @brooklynrob @toshaellison @mcleo-d

**Comment by aitana16** [comment]
@mindthegab @maoo Recurring PMC meetings have been cancelled (on both the FINOS Programs calendar and Webex) and a notice has been added to the [Program](https://finosfoundation.atlassian.net/wiki/spaces/DT/overview?homepageId=327090198) and [PMC](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/329383939/PMC) homepages

**Comment by mindthegab** [comment]
Thanks @aitana16, I've slightly updated the NOTICE to use Confluence Macros and reference the decision link. For the future, feel free to use this approach as a standard for notices on the wiki.

**Comment by maoo** [comment]
All done! Let's keep the issue open until changes are reflected in Bitergia (should be 1/2 days).

**Comment by maoo** [comment]
Done! metrics.finos.org is now updated
