### ISSUE TITLE
Morph Financial Objects Program  into multiple Projects

### ISSUE THREAD

**Issue by mindthegab** [finos/finos-pmcs#42]
Per VOTE on [FO PMC list](https://groups.google.com/a/finos.org/forum/#!topic/fo-pmc/AS-5cpxViQQ), the PMC has decided to disband and contained projects to continue as Top-Level.

So please execute on the following tasks:

 - [x] @maoo Morph all FO projects to be "Top Level" project in our finos.github.io catalog, retaining the existing lifecycle stage
- [x] @aitana16 cancel ongoing PMC meetings on webex
- [x] @aitana16 - add to the Program Wiki page the notice that the program has been disbanded and projects continue as top level projects.

NOTE: There's a parallel activity to explore whether the FO project, Alloy and Security Reference should work closely together which @brooklynrob will be looking at. This activity is disconnected and parallel and should not be a blocker to progress on this issue

/CC @finos/fo-pmc @donbasuno @toshaellison @brooklynrob @mcleo-d

**Comment by aitana16** [comment]
@mindthegab @maoo 
Recurring PMC meetings have been cancelled (on both the FINOS Programs calendar and Webex) and a notice has been added to the [Program](https://finosfoundation.atlassian.net/wiki/spaces/FO/overview) and [PMC](https://finosfoundation.atlassian.net/wiki/spaces/FO/pages/123437085/PMC) homepages

**Comment by maoo** [comment]
All done! Let's keep the issue open until changes are reflected in Bitergia (should be 1/2 days).

**Comment by maoo** [comment]
Done! metrics.finos.org is now updated
